Name:           ros-hydro-twitter-bootstrap
Version:        0.0.1
Release:        0%{?dist}
Summary:        ROS twitter_bootstrap package

Group:          Development/Libraries
License:        MIT
URL:            http://getbootstrap.com
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-hydro-catkin

%description
This package contains the source for Bootstrap and exposes it to catkin in a way
that makes it useable within ROS nodes which create webpages. All code under
bootstrap is licensed and authored according to the original documentation of
that package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Oct 23 2014 Nick Hawes <n.a.hawes@cs.bham.ac.uk> - 0.0.1-0
- Autogenerated by Bloom

